# Generated by Django 5.0.3 on 2024-04-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0002_alter_adminhod_options_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackstaffs',
            name='feedback_reply',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='feedbackstudent',
            name='feedback_reply',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
    ]
