# Generated by Django 5.0.3 on 2024-04-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0004_rename_feedbackstaffs_feedbackstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackstaff',
            name='theme',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='feedbackstudent',
            name='theme',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема'),
        ),
    ]
