# Generated by Django 5.0.3 on 2024-04-05 22:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0006_adminhod_phone_staff_phone_student_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackstaff',
            options={'verbose_name': 'Обратная связь сотрудника', 'verbose_name_plural': 'Обратная связь сотрудника'},
        ),
        migrations.AlterModelOptions(
            name='feedbackstudent',
            options={'verbose_name': 'Обратная связь студента', 'verbose_name_plural': 'Обратная связь студента'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Персонал', 'verbose_name_plural': 'Персонал'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='session_end_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='session_start_year',
        ),
        migrations.CreateModel(
            name='SessionYearModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_start_year', models.DateField(verbose_name='Начало сессии')),
                ('session_end_year', models.DateField(verbose_name='Конец сессии')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management_app.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
            },
        ),
    ]
